### PR TITLE
Adapted csma80215.cc initialize() to Ieee802154Mac.cc initialize() to solve errors from Issue #15

### PR DESCRIPTION
**Pull request by michaelkirsche**
Here's the fix for the error described in issue #15

Original Code:
https://github.com/aarizaq/inetmanet-2.0/commit/f2b0b3a9bdb259dee5740c32de13a60522641cdc

Fix:
https://github.com/michaelkirsche/inetmanet-2.0/commit/33adcc60c8ae2b6fb85806254d4e0c40983e6647

### CODE REVIEW

**Comment by aarizaq** [comment]
Thanks, I have uploaded a patch that should solve the problem and also simplify a bit the code

Now the code check that the address is EUI-64

https://github.com/aarizaq/inetmanet-2.0/commit/40bb8642feba13c6a7e41d37c50a74227aa8c6f0

De: Michael Kirsche [mailto:notifications@github.com] 
Enviado el: martes, 08 de octubre de 2013 21:05
Para: aarizaq/inetmanet-2.0
Asunto: [inetmanet-2.0] Adapted csma80215.cc initialize() to Ieee802154Mac.cc initialize() to solve errors from Issue #15 (#16)

Here's the fix for the error described in issue  https://github.com/aarizaq/inetmanet-2.0/issues/15 #15

Original Code:
 https://github.com/aarizaq/inetmanet-2.0/commit/f2b0b3a9bdb259dee5740c32de13a60522641cdc f2b0b3a

Fix:
michaelkirsche@ https://github.com/michaelkirsche/inetmanet-2.0/commit/33adcc60c8ae2b6fb85806254d4e0c40983e6647 33adcc6

---

You can merge this Pull Request by running

  git pull  https://github.com/michaelkirsche/inetmanet-2.0 https://github.com/michaelkirsche/inetmanet-2.0 802154patch

Or view, comment on, or merge it at:

   https://github.com/aarizaq/inetmanet-2.0/pull/16 https://github.com/aarizaq/inetmanet-2.0/pull/16

Commit Summary
-   Adapted csma80215.cc initialize() to Ieee802154Mac.cc initialize() to solve errors raised in commit

File Changes
-   M  https://github.com/aarizaq/inetmanet-2.0/pull/16/files#diff-0 src/wpan/linklayer/ieee802154/mac/csma802154.cc (19) 

Patch Links:
-   https://github.com/aarizaq/inetmanet-2.0/pull/16.patch
-   https://github.com/aarizaq/inetmanet-2.0/pull/16.diff

**Comment by michaelkirsche** [comment]
Hi,

almost... you forgot to set the aExtendedAddress in csma802154.cc like it's done in Ieee802154Mac.cc

So a plain 'aExtendedAddress = macaddress;' in 'csma802154cc' at line 62 after or before 'iface=NULL;' is needed.

Seems like I am mostly using the CSMA-MAC version and you the plain MAC without CSMA :)

**Comment by aarizaq** [comment]
aExtendedAddress is used in the Ieee802154mac code not in the csma version, it isn't necessary to initialize this value in csma802154::initialize. You modification is correct but I have decided finally to use MACAddress::generateAutoAddress() and avoid the possible repetition of a mac address with other interfaces

**Comment by michaelkirsche** [comment]
Yes, `aExtendedAddress` is implemented and used in the `Ieee802154Mac` code... but `csma802154` uses it too!

In `void csma802154::handleUpperMsg(cPacket *msg)` -> the function `dest = macModule->getMacAddr();` is called to get the source address of a node. This function refers to `IE3ADDR getMacAddr() {return aExtendedAddress;}` in `Ieee802154Mac.h` (through the inclusion of this header file in `csma802154.h`).

So `aExtendedAddress` needs to be set in csma802154 mac too, or else the source address of outgoing messages is 00-00-00-00-00-00... which in the end leads to problems for higher layer protocols like neighbor discovery etc.

I would therefore recommend that `aExtendedAddress` is set to macaddress after the `iface=NULL;` operation in csma802154.

Best regards,
Michael

**Comment by aarizaq** [comment]
I have uploaded some modifications that should solve this problem, I sincerely wait that the modifications don't provoke side effect

**Comment by michaelkirsche** [comment]
I didn't found any problems for this last commit, the modifications are clear and helpful! Thanks a lot for the quick fix, I will merge my own fork with your newest commits.
I'll let you know if I find any other problems.

Best regards,
Michael

**Pull request closed without merging**
